# Generated by Django 3.2.9 on 2021-12-23 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_hostingplace'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hostingplace',
            name='airConditioning',
        ),
        migrations.RemoveField(
            model_name='hostingplace',
            name='bar',
        ),
        migrations.RemoveField(
            model_name='hostingplace',
            name='breakfast',
        ),
        migrations.RemoveField(
            model_name='hostingplace',
            name='doubleBeds',
        ),
        migrations.RemoveField(
            model_name='hostingplace',
            name='electricity',
        ),
        migrations.RemoveField(
            model_name='hostingplace',
            name='freeWiFi',
        ),
        migrations.RemoveField(
            model_name='hostingplace',
            name='parking',
        ),
        migrations.RemoveField(
            model_name='hostingplace',
            name='picture',
        ),
        migrations.RemoveField(
            model_name='hostingplace',
            name='showers',
        ),
        migrations.RemoveField(
            model_name='hostingplace',
            name='singleBeds',
        ),
        migrations.AlterField(
            model_name='hostingplace',
            name='fireplace',
            field=models.BooleanField(default=False),
        ),
    ]
