# Generated by Django 3.2.9 on 2021-12-23 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20211223_2213'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostingplace',
            name='airConditioning',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hostingplace',
            name='bar',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hostingplace',
            name='breakfast',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hostingplace',
            name='doubleBeds',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hostingplace',
            name='electricity',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hostingplace',
            name='freeWiFi',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hostingplace',
            name='parking',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hostingplace',
            name='picture',
            field=models.ImageField(blank=True, upload_to='static\\media\\host_pics'),
        ),
        migrations.AddField(
            model_name='hostingplace',
            name='showers',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hostingplace',
            name='singleBeds',
            field=models.BooleanField(default=False),
        ),
    ]
