# Generated by Django 3.2.9 on 2021-12-23 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20211223_2215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hostingplace',
            name='picture',
        ),
    ]
