# Generated by Django 3.2.9 on 2021-12-23 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_hostingplace_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hostingplace',
            name='picture',
        ),
    ]
