# Generated by Django 3.2.9 on 2021-12-26 22:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0004_alter_userprofileinfo_picture'),
        ('main', '0010_remove_hostingplace_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostingplace',
            name='user',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='registry.userprofileinfo'),
            preserve_default=False,
        ),
    ]
