# Generated by Django 3.2.9 on 2021-12-27 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20211227_0203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostingplace',
            name='username',
            field=models.CharField(default='', max_length=200),
        ),
    ]
