# Generated by Django 3.2.9 on 2021-12-28 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_guideinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guideinfo',
            name='name',
        ),
    ]
