# Generated by Django 3.2.9 on 2021-12-30 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_guideinfo_routes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guideinfo',
            name='cost',
            field=models.FloatField(max_length=200),
        ),
    ]
