# Generated by Django 3.2.9 on 2022-01-01 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_guideinfo_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostingplace',
            name='picture',
            field=models.ImageField(blank=True, upload_to='static\\media\\host_pics'),
        ),
    ]
